export enum Types {
  GET_ALL_FOODS = 'GET_ALL_FOODS',
  GET_FOOD = 'GET_FOOD',
  TOGGLE_GROCERIES_EDIT_MODE = 'TOGGLE_GROCERIES_EDIT_MODE',
  TOGGLE_GROCERIES_MODAL = 'TOGGLE_GROCERIES_MODAL',
  SET_SELECTED_FOOD = 'SET_SELECTED_FOOD',
  GET_GROCERIES = 'GET_GROCERIES',
  ADD_FOOD = 'ADD_FOOD',
  EDIT_FOOD = 'EDIT_FOOD',
  DELETE_FOOD = 'DELETE_FOOD',

  RANDOMIZE_MEALS = 'RANDOMIZE_MEALS',
  ADD_FAVORITE_MEAL = 'ADD_FAVORITE_MEAL',
  REMOVE_FAVORITE_MEAL = 'REMOVE_FAVORITE_MEAL',

  GET_ALL_MEALS = 'GET_ALL_MEALS',
  GET_MEAL = 'GET_MEAL',
  ADD_MEAL = 'ADD_MEAL',
  EDIT_MEAL = 'EDIT_MEAL',
  DELETE_MEAL = 'DELETE_MEAL',
}
