export enum Types {
    GET_ALL_FOODS = 'GET_ALL_FOODS',
    GET_FOOD = 'GET_FOOD',
    TOGGLE_GROCERIES_EDIT_MODE = 'TOGGLE_GROCERIES_EDIT_MODE',
    TOGGLE_GROCERIES_MODAL = 'TOGGLE_GROCERIES_MODAL',
    GET_GROCERIES = 'GET_GROCERIES',
    ADD_FOOD = 'ADD_FOOD',
    EDIT_FOOD = 'EDIT_FOOD',
    DELETE_FOOD = 'DELETE_FOOD',

    GET_ALL_MEALS = 'GET_ALL_MEALS',
    GET_MEAL = 'GET_MEAL',
    ADD_MEAL = 'ADD_MEAL',
    EDIT_MEAL = 'EDIT_MEAL',
    DELETE_MEAL = 'DELETE_MEAL',
}
